image: node:latest

before_script:
  - npm install

stages:
  - lint
  - test
  - deploy

lint:
  stage: lint
  script:
    - npm run lint

# test:
#   stage: test
#   script:

deploy:
  only:
    - deploy
    - master
  stage: deploy
  script:
    - (docker stop label-2-fe-app || true) && (docker rm label-2-fe-app || true)
    - docker build -t label-2-fe-app .
    - docker run --name label-2-fe-app -p 3000:80 -d label-2-fe-app